### PR TITLE
Create feat_val.quz

### PR DESCRIPTION
**Pull request by josephinetherese**
add language-specific features for Cusco Quechua

### CODE REVIEW

**Comment by dan-zeman** [comment]
What is the difference between proposed `Voice=Caus` and already existing [Voice=Cau](https://universaldependencies.org/u/feat/Voice.html#Cau)?

**Comment by dan-zeman** [comment]
Does `Inclusive[psor]=Yes` refer to [clusivity](https://universaldependencies.org/u/feat/Clusivity.html)? Shouldn't it then be `Clusivity[psor]=In`?

**Comment by dan-zeman** [comment]
Does `Case=Distr` stand for [distributive](https://universaldependencies.org/u/feat/Case.html#Dis)?

Does `Case=Term` stand for [terminative](https://universaldependencies.org/u/feat/Case.html#Ter)?

**Comment by dan-zeman** [comment]
Is `Mood=Obligative` substantially different from [necessitative](https://universaldependencies.org/u/feat/Mood.html#Nec)?

**Comment by josephinetherese** [comment]
Thank you for drawing our attention to those, I think you are correct on all counts. I have updated the file to reflect this.

**Pull request merged**
