### PR TITLE
complete the list of Kazakh auxiliary verbs

### PR DESCRIPTION
**Pull request by IlnarSelimcan**
Based on:

- UD_Kazakh_KTB
- Оразбаева, Ф.Ш., Г. Сағидолда, Б. Қасым, А. Қобыланова, Қ. Есенова, Ұ. Исабекова,Қ. Қасабек, Ж. Балтабаев, Қ. Мұхамади, Р. Рахметова & Ж. Көпбаева. 2012.Қазіргі қазақ тілі. Алматы: Нур-Принт.
- Muhamedowa, Raihan. 2016. Kazakh: a comprehensive grammar. London: Routledge.

### CODE REVIEW

**Comment by dan-zeman** [comment]
Thanks. Could you please also document the function of the individual auxiliaries on the Kazakh-specific documentation page. [The instructions are here.](https://universaldependencies.org/contributing_language_specific.html)

**Comment by IlnarSelimcan** [comment]
Hi @dan-zeman , I'll have a look. Documentation needs updating to v2, but most likely this will be done for the 2.8 release, not 2.7.

**Comment by dan-zeman** [comment]
Thanks. Updating all the old pages is probably quite a bit of work, although useful of course. But Kazakh still lacks the summary page (`_kk/index.md`) that is now required for all languages. That would be perhaps less work, and it could be cloned from [Turkish](https://github.com/UniversalDependencies/docs/blob/pages-source/_tr/index.md) and edited.

**Comment by dan-zeman** [comment]
This pull request is outdated, as auxiliaries are no longer registered in the source code of the validator. Now https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/langspec/specify_auxiliary.pl?lcode=kk is the way to go.

**Pull request closed without merging**
