### PR TITLE
added PT auxiliares and specific deprels for PT

### PR DESCRIPTION
**Pull request by arademaker**

### CODE REVIEW

**Comment by dan-zeman** [comment]
Hi @arademaker, what about the previous pull request (#42)? Have you seen [my comment](https://github.com/UniversalDependencies/tools/pull/42#pullrequestreview-218367779)?

**Comment by arademaker** [comment]
Hi @dan-zeman , yes I saw it but I had delegated the answer to @claudiafreitas ! The creation of the index page will take a little more time, I had to understand it first. 

BTW, we still have ~4K erros of type `Punctuation must not cause non-projectivity of nodes` . Are you going to be strict about it? That is, treebanks with does errors will not be included in the release?

**Comment by dan-zeman** [comment]
> Hi @dan-zeman , yes I saw it but I had delegated the answer to @claudiafreitas ! The creation of the index page will take a little more time, I had to understand it first.

OK, I am going to tentatively merge the pull request now. If it later turns out that some of the verbs are not auxiliary in the UD sense, they can be removed again.
 
> BTW, we still have ~4K erros of type `Punctuation must not cause non-projectivity of nodes` . Are you going to be strict about it? That is, treebanks with does errors will not be included in the release?

I am afraid that we will have to postpone being strict to the next release, otherwise we would lose too many treebanks now. On the other hand, most of the punctuation errors can be wiped out automatically (e.g., using Udapi ud.FixPunct). Or do you want to review them individually because they could signal other types of errors?

**Comment by arademaker** [comment]
> Or do you want to review them individually because they could signal other types of errors?
 
yes. And I don’t know what rule the Udapi is applying

**Comment by lauma** [comment]
By the way. Udapi ud.FixPunct changes only problematic punctuation attachment or it redoes all punctuation?

**Comment by dan-zeman** [comment]
@martinpopel 
The [documentation of Udapi](https://udapi.readthedocs.io/en/latest/_modules/udapi/block/ud/fixpunct.html) does not answer this question explicitly but my understanding is that it redoes everything. (One could argue what are problematic cases. Those that the current validator reports as errors? Or also those that do not adhere to the guidelines but the validator does not report them? Anyways, even if Udapi attempts to redo everything, it cannot do everything perfectly, as the documentation warns. But it should be pretty good at removing nonprojectivity.

**Comment by Stormur** [comment]
Unfortunately, I have tried Udapi FixPunct it on a sample of our database and, while correcting some errors, it generated new ones detected by the validator in the same sentence and also in previously corrected sentences. So I would be reluctant to run it on our treebank.

**Comment by martinpopel** [comment]
Hi, I am the author of [ud.FixPunct](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/fixpunct.py). In most cases, the attachment of punctuation is uniquely defined by the UD guidelines, and these are the rules `ud.FixPunct` is intended to follow. Basically, it redoes all punctuation, just in cases where multiple parents are allowed by the guidelines (depending on what is considered to be a *unit*), it prefers the original attachment. Of course, there are some cases which are difficult to fix automatically. And of course, there may still be bugs (or suboptimal heuristics for edge cases) in `ud.FixPunct` - in that case (@Stormur), please report them via Udapi issues with a conllu sample, similarly as done in https://github.com/udapi/udapi-python/issues/52.

**Pull request merged**
